version: 0.2
phases:
  build:
    commands:
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce
      - server docker start
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 239302956728.dkr.ecr.us-east-1.amazonaws.com
      - sudo docker build -t laravel .
      - sudo docker tag laravel:latest 239302956728.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
      - sudo docker push 239302956728.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
