version: "3.7"

services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: secretic
        container_name: secretic-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - s3vol/app:/var/www
        networks:
            - secretic

    db:
        image: mysql:8.0
        container_name: secretic-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - s3vol/mysql:/var/lib/mysql
        networks:
            - secretic

    nginx:
        image: nginx:1.25-alpine
        container_name: secretic-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - s3vol/app:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - secretic
  

volumes:
  s3vol:
    driver: rexray/s3fs
    driver_opts:
      S3FS_OPTIONS: ${S3FS_OPTIONS}
      S3FS_BUCKET: ${AWS_BUCKET}
      S3FS_ACCESSKEY: ${AWS_ACCESS_KEY_ID}
      S3FS_SECRETKEY: ${AWS_SECRET_ACCESS_KEY}

networks:
    secretic:
        driver: bridge
