version: "3.7"

services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: secretic
        container_name: secretic-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - efs/app:/var/www
        networks:
            - secretic

    db:
        image: mysql:8.0
        container_name: secretic-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - efs/mysql:/var/lib/mysql
        networks:
            - secretic

    nginx:
        image: nginx:1.25-alpine
        container_name: secretic-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
           - efs/app:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - secretic
  

volumes:
  efs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${EFS_DNSNAME},nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
      device: ":/"

networks:
    secretic:
        driver: bridge